name: Test Hello function
run-name: ${{github.actor}} is testing Hello function
on: [push, pull_request]
jobs:
  Execute-Hello-function:
    runs-on: ubuntu-latest
    steps:
      - run: pip install python
      - run: py hello.py